data:extend {
    {
        type = 'int-setting',
        name = 'bottleneck-signals-per-tick',
        setting_type = 'runtime-global',
        default_value = 40,
        maximum_value = 2000,
        minimum_value = 1,
        order = 'bottleneck-aa'
    },
    {
        type = 'string-setting',
        name = 'bottleneck-show-working',
        setting_type = 'runtime-global',
        default_value = 'green',
        allowed_values = {
            'off',
            'green',
            'red',
            'yellow',
            'blue',
            'redx',
            'yellowmin',
            'offsmall',
            'greensmall',
            'redsmall',
            'yellowsmall',
            'bluesmall',
            'redxsmall',
            'yellowminsmall'
        },
        order = 'bottleneck-ab'
    },
    {
        type = 'string-setting',
        name = 'bottleneck-show-no_power',
        setting_type = 'runtime-global',
        default_value = 'redx',
        allowed_values = {
            'off',
            'green',
            'red',
            'yellow',
            'blue',
            'redx',
            'yellowmin',
            'offsmall',
            'greensmall',
            'redsmall',
            'yellowsmall',
            'bluesmall',
            'redxsmall',
            'yellowminsmall'
        },
        order = 'bottleneck-ac'
    },
    {
        type = 'string-setting',
        name = 'bottleneck-show-no_fuel',
        setting_type = 'runtime-global',
        default_value = 'redx',
        allowed_values = {
            'off',
            'green',
            'red',
            'yellow',
            'blue',
            'redx',
            'yellowmin',
            'offsmall',
            'greensmall',
            'redsmall',
            'yellowsmall',
            'bluesmall',
            'redxsmall',
            'yellowminsmall'
        },
        order = 'bottleneck-ad'
    },
    {
        type = 'string-setting',
        name = 'bottleneck-show-no_recipe',
        setting_type = 'runtime-global',
        default_value = 'off',
        allowed_values = {
            'off',
            'green',
            'red',
            'yellow',
            'blue',
            'redx',
            'yellowmin',
            'offsmall',
            'greensmall',
            'redsmall',
            'yellowsmall',
            'bluesmall',
            'redxsmall',
            'yellowminsmall'
        },
        order = 'bottleneck-ae'
    },
    {
        type = 'string-setting',
        name = 'bottleneck-show-no_input_fluid',
        setting_type = 'runtime-global',
        default_value = 'red',
        allowed_values = {
            'off',
            'green',
            'red',
            'yellow',
            'blue',
            'redx',
            'yellowmin',
            'offsmall',
            'greensmall',
            'redsmall',
            'yellowsmall',
            'bluesmall',
            'redxsmall',
            'yellowminsmall'
        },
        order = 'bottleneck-af'
    },
    {
        type = 'string-setting',
        name = 'bottleneck-show-no_research_in_progress',
        setting_type = 'runtime-global',
        default_value = 'off',
        allowed_values = {
            'off',
            'green',
            'red',
            'yellow',
            'blue',
            'redx',
            'yellowmin',
            'offsmall',
            'greensmall',
            'redsmall',
            'yellowsmall',
            'bluesmall',
            'redxsmall',
            'yellowminsmall'
        },
        order = 'bottleneck-ag'
    },
    {
        type = 'string-setting',
        name = 'bottleneck-show-no_minable_resources',
        setting_type = 'runtime-global',
        default_value = 'red',
        allowed_values = {
            'off',
            'green',
            'red',
            'yellow',
            'blue',
            'redx',
            'yellowmin',
            'offsmall',
            'greensmall',
            'redsmall',
            'yellowsmall',
            'bluesmall',
            'redxsmall',
            'yellowminsmall'
        },
        order = 'bottleneck-ah'
    },
    {
        type = 'string-setting',
        name = 'bottleneck-show-low_input_fluid',
        setting_type = 'runtime-global',
        default_value = 'red',
        allowed_values = {
            'off',
            'green',
            'red',
            'yellow',
            'blue',
            'redx',
            'yellowmin',
            'offsmall',
            'greensmall',
            'redsmall',
            'yellowsmall',
            'bluesmall',
            'redxsmall',
            'yellowminsmall'
        },
        order = 'bottleneck-ai'
    },
    {
        type = 'string-setting',
        name = 'bottleneck-show-low_power',
        setting_type = 'runtime-global',
        default_value = 'redx',
        allowed_values = {
            'off',
            'green',
            'red',
            'yellow',
            'blue',
            'redx',
            'yellowmin',
            'offsmall',
            'greensmall',
            'redsmall',
            'yellowsmall',
            'bluesmall',
            'redxsmall',
            'yellowminsmall'
        },
        order = 'bottleneck-aj'
    },
    {
        type = 'string-setting',
        name = 'bottleneck-show-disabled_by_control_behavior',
        setting_type = 'runtime-global',
        default_value = 'off',
        allowed_values = {
            'off',
            'green',
            'red',
            'yellow',
            'blue',
            'redx',
            'yellowmin',
            'offsmall',
            'greensmall',
            'redsmall',
            'yellowsmall',
            'bluesmall',
            'redxsmall',
            'yellowminsmall'
        },
        order = 'bottleneck-ak'
    },
    {
        type = 'string-setting',
        name = 'bottleneck-show-disabled_by_script',
        setting_type = 'runtime-global',
        default_value = 'off',
        allowed_values = {
            'off',
            'green',
            'red',
            'yellow',
            'blue',
            'redx',
            'yellowmin',
            'offsmall',
            'greensmall',
            'redsmall',
            'yellowsmall',
            'bluesmall',
            'redxsmall',
            'yellowminsmall'
        },
        order = 'bottleneck-al'
    },
    {
        type = 'string-setting',
        name = 'bottleneck-show-fluid_ingredient_shortage',
        setting_type = 'runtime-global',
        default_value = 'red',
        allowed_values = {
            'off',
            'green',
            'red',
            'yellow',
            'blue',
            'redx',
            'yellowmin',
            'offsmall',
            'greensmall',
            'redsmall',
            'yellowsmall',
            'bluesmall',
            'redxsmall',
            'yellowminsmall'
        },
        order = 'bottleneck-am'
    },
    {
        type = 'string-setting',
        name = 'bottleneck-show-fluid_production_overload',
        setting_type = 'runtime-global',
        default_value = 'yellow',
        allowed_values = {
            'off',
            'green',
            'red',
            'yellow',
            'blue',
            'redx',
            'yellowmin',
            'offsmall',
            'greensmall',
            'redsmall',
            'yellowsmall',
            'bluesmall',
            'redxsmall',
            'yellowminsmall'
        },
        order = 'bottleneck-an'
    },
    {
        type = 'string-setting',
        name = 'bottleneck-show-item_ingredient_shortage',
        setting_type = 'runtime-global',
        default_value = 'red',
        allowed_values = {
            'off',
            'green',
            'red',
            'yellow',
            'blue',
            'redx',
            'yellowmin',
            'offsmall',
            'greensmall',
            'redsmall',
            'yellowsmall',
            'bluesmall',
            'redxsmall',
            'yellowminsmall'
        },
        order = 'bottleneck-ao'
    },
    {
        type = 'string-setting',
        name = 'bottleneck-show-item_production_overload',
        setting_type = 'runtime-global',
        default_value = 'yellow',
        allowed_values = {
            'off',
            'green',
            'red',
            'yellow',
            'blue',
            'redx',
            'yellowmin',
            'offsmall',
            'greensmall',
            'redsmall',
            'yellowsmall',
            'bluesmall',
            'redxsmall',
            'yellowminsmall'
        },
        order = 'bottleneck-ap'
    },
    {
        type = 'string-setting',
        name = 'bottleneck-show-marked_for_deconstruction',
        setting_type = 'runtime-global',
        default_value = 'off',
        allowed_values = {
            'off',
            'green',
            'red',
            'yellow',
            'blue',
            'redx',
            'yellowmin',
            'offsmall',
            'greensmall',
            'redsmall',
            'yellowsmall',
            'bluesmall',
            'redxsmall',
            'yellowminsmall'
        },
        order = 'bottleneck-aq'
    },
    {
        type = 'string-setting',
        name = 'bottleneck-show-missing_required_fluid',
        setting_type = 'runtime-global',
        default_value = 'red',
        allowed_values = {
            'off',
            'green',
            'red',
            'yellow',
            'blue',
            'redx',
            'yellowmin',
            'offsmall',
            'greensmall',
            'redsmall',
            'yellowsmall',
            'bluesmall',
            'redxsmall',
            'yellowminsmall'
        },
        order = 'bottleneck-ar'
    },
    {
        type = 'string-setting',
        name = 'bottleneck-show-missing_science_packs',
        setting_type = 'runtime-global',
        default_value = 'red',
        allowed_values = {
            'off',
            'green',
            'red',
            'yellow',
            'blue',
            'redx',
            'yellowmin',
            'offsmall',
            'greensmall',
            'redsmall',
            'yellowsmall',
            'bluesmall',
            'redxsmall',
            'yellowminsmall'
        },
        order = 'bottleneck-as'
    },
    {
        type = 'string-setting',
        name = 'bottleneck-show-waiting_for_source_items',
        setting_type = 'runtime-global',
        default_value = 'red',
        allowed_values = {
            'off',
            'green',
            'red',
            'yellow',
            'blue',
            'redx',
            'yellowmin',
            'offsmall',
            'greensmall',
            'redsmall',
            'yellowsmall',
            'bluesmall',
            'redxsmall',
            'yellowminsmall'
        },
        order = 'bottleneck-at'
    },
    {
        type = 'string-setting',
        name = 'bottleneck-show-waiting_for_space_in_destination',
        setting_type = 'runtime-global',
        default_value = 'yellow',
        allowed_values = {
            'off',
            'green',
            'red',
            'yellow',
            'blue',
            'redx',
            'yellowmin',
            'offsmall',
            'greensmall',
            'redsmall',
            'yellowsmall',
            'bluesmall',
            'redxsmall',
            'yellowminsmall'
        },
        order = 'bottleneck-au'
    }
}
